name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          # Workaround to handle multiple checkout of the same repository.
          # see https://github.com/actions/checkout/issues/211#issuecomment-611096511
          path: name_of_test 
      - name: Enviroment Variables
        run: printenv | sort
      - name: EC2 Metadata
        run: |
            curl -s http://169.254.169.254/latest/meta-data/instance-type
            printf '\n'
            curl -s http://169.254.169.254/latest/meta-data/instance-life-cycle
