# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # - run: sudo chown -R $USER:$USER /home/github/actions-runner/_work/
      - uses: actions/checkout@v2
        with:
          path: name_of_test 
      - name: EC2 Metadata
        run: |
            sudo yum install jq
            curl http://169.254.169.254/latest/meta-data/ 
      - name: Reach Internal
        run: curl -I https://atlantis.werally.com
